- general_tools/en_indexer.sh
> Use real path to indexer to actually trigger the re-building the index

- ta/etherpad_to_dokuwiki.py
Adds out-of-date links to the ta_import log report
Resolves unfoldingWord-dev/Door43#167
> Generate Report of Bad tA Links

- uwb/ep_chunk.py
Implementes the same text fixes found ep_update.py.
Resolves unfoldingWord-dev/tools#115
> Text fixes in ep_chunk.py

- obs/book/pdf_export.sh
- obs/export.py
These two changes add new functionality to the PDF generator script that make it easier to debug and adjust what's going on.
> Add helpful options for debugging typesetter

- obs/export_templates.sh
Relates to unfoldingWord-dev/Door43#246
> Bash script to export ODT template in DOCX and OCT formats

- ta/etherpad_to_docx.py
- ta/etherpad_to_uw.py
Fix italic regex
Save directly to the uW template file.
Fix bug in hyperlink regex
Fix italic regex again
Colon at end of line needs to be followed by 2 line feeds for pandoc.
Line feeds in block quotes need to have a br tag for pandoc.
> Add script to create tA for unfoldingword.org

- obs/json/obs_inprogress.py
* Added some more comments
* Reformatted to be more in compliance with PEP8 standards so it is easier to debug using PyCharm or IntelliJ
* Updated ambiguous variable names
* Removed some code that is no longer needed
> Refactoring the obs_inprogress.py script file

- obs/js/reveal_export.py
* Reformatted to be more in compliance with PEP8 standards so it is easier to debug using PyCharm or IntelliJ
* Removed some code that is no longer needed
* Use path relative to the script to locate other files in the repository rather than a hard-coded path
> Refactoring the reveal_export.py script

- ta/etherpad_to_dokuwiki.py
Also added the 'Process' manual
Resolves unfoldingWord-dev/Door43#364
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/136)
> Make all dependencies in tA export be bulleted

- obs/json/json_import.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/138)
> Added obs_import.py

- obs/json/json_import.py
- obs/json/json_tn_export.py
- obs/json/json_tn_import.py
- obs/json/json_tw_import.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/139)
> Merge of richmahn/tools into tools

- obs/book/pdf_export.sh
- obs/export.py
- obs/tex/place-reference.tex
- uw/update_catalog.py
- uwb/bible/pdf_export.sh
- uwb/status.py
- uwb/status_query.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/143)
> UDB and ULB PDF generation, Fixes for OBS export

- gogs/config-SAMPLE.py
- gogs/push_repo.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/146)
> richmahn into master

- .gitignore
- ta/etherpad_to_dokuwiki.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/148)
> Make all YAML content italic.

- uw/update_catalog.py
- uwb/api_publish.py
Also reformatted to be PEP8 compliant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/154)
> Automatically find new Bible versions

- uwb/check_usfm.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/169)
> USFM chapter and verse checks

- uwb/tq_export.sh
- uwb/tq_export_full.sh
- uwb/tw_export.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/174)
> Added tQ full and individual books

- uwb/tq_export_full.sh
- uwb/tw_export.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/175)
> Fixes to PDF scripts

- ta/md_convert/export_md_to_pdf.sh
- ta/md_convert/md_to_html_export.py
- ta/md_convert/toc_template.xsl
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/177)
> Tools for Converting tA MD to HTML and PDF

- ta/md_convert/export_md_to_pdf.sh
- ta/md_convert/footer.html
- ta/md_convert/header.html
- ta/md_convert/md_to_html_export.py
- ta/md_convert/toc_template.xsl
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/178)
> More changes to MD converter

- ta/ru_html_export.py
- ta/ru_pdf_export.sh
- uwb/export.py
- uwb/ru_tw_html_export.py
- uwb/ru_tw_pdf_export.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/180)
> richmahn into uw-dev

- gogs/gogs.py
- uwb/export.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/181)
> Changes to Bible exporter and Gogs

- uwb/export.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/183)
> Uses new usfm_tools python library

- uwb/tn_export.sh
- uwb/tq_export.sh
- uwb/tq_export_full.sh
- uwb/tw_export.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/184)
> Updated version and remove .0

- uwb/put_chunks_into_notes.py
There is not change if functionality, mostly reformatting so the file passes PEP 8 inspections.
This is preparation for issue https://github.com/unfoldingWord-dev/door43.org/issues/336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/186)
> Make the file pass PEP 8 inspection

- uwb/put_chunks_into_notes.py
Closes https://github.com/unfoldingWord-dev/door43.org/issues/336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/tools/187)
> Issue #336: Invalid Chunk Page Creation in DW
